---
title: "3B. Harmonizing Spatial Data"
author: "iEcoLab"
date: "May 29, 2024"
output:
  html_document:
    df_print: paged
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, results = 'hide') 
```
The following document demonstrates how to harmonize spatial datasets for this example.

### **Loading in Packages**
```{r loading packages}
library(tidyverse) 
library(here) #relative working directory
library(tigris) #geopolitical boundary spatial files
library(sf) #spatial harmonization
library(raster) #to deal with rasters
library(terra) #dealing with rasters and shps at the same time
library(exactextractr) #for extracting ensemble values to subcounties
```

### **Loading Spatial Files**
```{r loading spatial files}
#file path
shp_path <- here("2_Obtain_Hub_Spatial_Data", "2B_Obtain_Spatial_Data", "Raw_Spatial_Data") %>%
  str_remove("/3_Clean_Harmonize_Data/3B_Harmonize_Spatial_Data")

#----establishment risk----
establishment <- rast(file.path(shp_path, "slftoh_ensemble_mean_crop.tif"))

#----1km grid----
#UTM zone 17
km_grid_PA17 <- st_read(file.path(shp_path, "PA_USNG", "PA_USNG_UTM17.shp")) %>%
  #adjusting crs for easier manipulation
  st_as_sf(coords = c("Easting", "Northing"), crs = 27700) %>%
  st_transform(4269) %>%
  #fixing column names and discrepancies
  dplyr::select(-c("OBJECTID", "OBJECTID_2")) %>%
  rename(Shape_Leng = "SHAPE_Leng",
         Shape_Area = "SHAPE_Area")

#UTM zone 18
km_grid_PA18 <- st_read(file.path(shp_path, "PA_USNG", "PA_USNG_UTM18.shp")) %>%
  st_as_sf(coords = c("Easting", "Northing"), crs = 27700) %>%
  st_transform(4269)

#combining UTM zones 17 and 18 for full PA 1km grid
km_grid <- rbind(km_grid_PA17, km_grid_PA18)

#----subcounties----
subcounties <- st_read(file.path(shp_path, "tl_2019_42_cousub", "tl_2019_42_cousub.shp")) %>%
  filter(NAME != "County subdivisions not defined")

#----counties----
counties <- tigris::counties("Pennsylvania", cb = TRUE)

#saving county outlines
st_write(counties, here("Spatial_Data_Harmonized", "county_outline", "county_outline.shp"), append = TRUE)

#----state map----
state <- tigris::states() %>%
  filter(STUSPS == "PA")

```


### **Cropping 1km Grid to PA Counties**
```{r making 1km county grids}
#all the counties in PA
counties_list <- c("Adams", "Allegheny", "Armstrong", "Beaver", "Bedford", "Berks", "Blair", "Bradford", "Bucks", "Butler", "Cambria", "Cameron", "Carbon", "Centre", "Chester", "Clarion", "Clearfield", "Clinton", "Columbia", "Crawford", "Cumberland", "Dauphin", "Delaware", "Elk", "Erie", "Fayette", "Forest", "Franklin", "Fulton", "Greene", "Huntingdon", "Indiana", "Jefferson", "Juniata", "Lackawanna", "Lancaster", "Lawrence", "Lebanon", "Lehigh", "Luzerne", "Lycoming", "McKean", "Mercer", "Mifflin", "Monroe", "Montgomery", "Montour", "Northampton", "Northumberland", "Perry", "Philadelphia", "Pike", "Potter", "Schuylkill", "Snyder", "Somerset", "Sullivan", "Susquehanna", "Tioga", "Union", "Venango", "Warren", "Washington", "Wayne", "Westmoreland", "Wyoming", "York")

#for loop to take each county and intersect with 1km grid (will take some time)
for (county_name in counties_list) {
#Filter the dataset for the current county
  county_data <- counties %>%
    filter(NAME == county_name)
  
  #cropping grid to extent of state so code runs quicker
  county_bbox <- st_bbox(county_data)
  county_bbox_buffered <- st_buffer(st_as_sfc(st_bbox(county_bbox)), dist = 1000)
  bbox_crop <- st_crop(km_grid, county_bbox_buffered)

  #intersecting county shape with 1km grid
  county_1km_grid <- st_intersection(county_data, bbox_crop)

  #assigning df name
  variable_name <- paste0(county_name, "_1km")
  assign(variable_name, county_1km_grid)
}

#Saving county 1km files
for (county_name in counties_list) {
  #defining names of county shp and getting them
  variable_name <- paste0(county_name, "_1km") 
  
  variable_name_df <- get(variable_name)
  
  #naming file
  file_name <- variable_name %>%
    gsub("\\.", "", .) %>%
    gsub("_1km", "", .)
  
  #saving file
  st_write(variable_name_df, here("Spatial_Data_Harmonized", "county_1km_grids", file_name), driver = "ESRI Shapefile", append = TRUE)
  
}

```


### **Extracting Establishment at Subcounty Level**
```{r extracting establishment for PA}
#extracting values from ensemble tif to subcounties
establishment_extract <- exact_extract(
  x = establishment, 
  y = subcounties,
  'mean')  

#turning output list in data frame and renaming column with risk values
establishment_extract <- data.frame(establishment_extract) %>%
  rename(establishment_value = establishment_extract)

#combining new df with risk values to old df with the geographic data
establishment_extract_subcounties <- bind_cols(subcounties, establishment_extract)

#saving file
st_write(establishment_extract_subcounties, here("Spatial_Data_Harmonized", "establishment_risk", "establishment_risk.shp"), append = TRUE)
```

### **Calculating Density of Hubs at Subcounty Level**
```{r hub density}
#PART 1: Getting hub data
  #list of hubs
  hub_types <- c("hospitals", "policeStations", "universities")

  hubs <- NULL
  
  for (type in hub_types) {
    #hub file path
    hubs_path <- file.path(here("3A_Clean_Hub_Data", "Hub_Data_Clean", 
                                paste0(type, ".csv"))) %>%
      str_remove("/3B_Harmonize_Spatial_Data")
    
    #finding and loading in files
    if(file.exists(hubs_path)) {
      df <- read.csv(hubs_path)
      
      hubs <- rbind(hubs, df)
    } else {
      print(paste("No file found for type:", type))
    }
  
    #converting from df to sf
    sf_hubs <- st_as_sf(hubs, coords = c("Longitude", "Latitude"), crs = 4269)
    
    assign("sf_hubs", sf_hubs)
}
    
#PART 2: making hub density layer
  #putting subcounties data into hub density layer
  hub_density <- subcounties
  
  #assigning hub density counts to each subcounty
  hub_density$hub_count <- lengths(st_intersects(subcounties, sf_hubs))

#saving file 
st_write(hub_density, here("Spatial_Data_Harmonized", "hub_density", "hub_density.shp"), append = TRUE)

```



