---
title: "Template for POI retrieval"
author: "Hannah Joseph"
output: html_document
---
This Rmd file is a template for filtering for pestHubMap points for your STATE.

```{r packages, include = FALSE, messages = FALSE, warning = FALSE}
library(data.table)
library(readr)
library(here)
library(tidyverse)
library(ggmap)
library(sf) 
library(magrittr)

#In case here sets to the wrong directory unload the package using this code and then reload above
# detach("package:here", unload = TRUE)

#rm(list = ls())

```

```{r loading in data, include = FALSE}
state_abbr <- "PA" #replace with your state abbreviation

POI <- fread(here("Pennsylvania.csv"), showProgress = FALSE) %>% #replace Pennsylvania with your state
  filter(duplicate_id == "")
```

```{r hospitals}

hospitals <- POI %>% 
  filter(grepl("hospitals|medical|healthcare"), main_category) %>% 
  filter(!grepl("restaurants|dining|tech"), business_category) %>% 
  distinct("geometry", .keepall = TRUE)

```

```{r police stations}

policestations <- POI %>% 
  filter(grepl("stations|police|department"), main_category) %>% 
  filter(!grepl("restaurants|dining|healthcare|tech"), business_category) %>% 
  distinct(Latitude, .keepall = TRUE)

```

```{r universities}
universities_filepath <- here("IPEDS.csv") %>%
  str_remove(paste0("/", state_abbr))
universities_original <- read.csv(college_filepath) %>%
  filter(STABBR == state_abbr)

universities <- universities_original %>%
  select(c("INSTNM", "ADDR","CITY", "STABBR", "ZIP", "latitude", "LONGITUD")) 

universities %<>% mutate(address = paste0(universities$ADDR, ", ", universities$CITY, ", ", universities$STABBR, " ", universities$ZIP),
         latitude = universities$latitude,
         longitude = universities$LONGITUD, 
         name = universities$INSTNM) %>%
  select(c("name", "address", "latitude", "longitude"))

```

```{r saving data}
#---- Rearranging columns for website----
dfs <- c("hospitals", "policestations", "universities")

for(df_name in dfs) {
  df <- get(df_name, envir = .GlobalEnv)
  
  #selecting only necessary columns
  necessary_cols <- c("name", "address", "city", "state", "postal_code", "latitude", "longitude")
  df <- df %>%
    select(all_of(necessary_cols))
  
  #combining address columns into one
  df$address <- paste(df$address, df$city, state_abbr, sep = ", ")
  df$address <- paste(df$address, df$postal_code, sep = " ")
  
  #removing redundant columns
  df <- select(df, name, address, latitude, longitude)
  
  #Renaming columns
  renamed_cols <- c(name = "name", address = "address", latitude = "latitude", longitude = "longitude")
  df <- rename(df, all_of(renamed_cols))
  
  assign(df_name, df, envir = .GlobalEnv)
}

#----saving CSV files ----
dfs2 <- c("hospitals", "policestations", "universities")

#Saving data tables
for(df_name in dfs2) {
  df <- get(df_name,envir = .GlobalEnv)
  #saving CSVs for every dataframe
  csv_file <- paste0(df_name, ".csv")
  write.csv(df, file = here("POI", csv_file), row.names = FALSE)
}
```